### PR TITLE
Feature/handlers

### PR DESCRIPTION
**Pull request by OidaTiftla**
Hi,
if you don't like the changes, don't mind and simply close this pull request 😄 

If the pull requests #236 and/or #237 are merged before, this pull request will cause a merge conflict. So if the other two pull requests are merged, I'll update this branch to merge cleanly into master 😅 

`variables` and `functions` are generalized into `handlers` (because later I'd like to add another `handler` called `api_extension`).

The backwards compatibility is kepts through some makros:
```
// -------- for backwards compatibility --------
#ifdef AREST_NUMBER_VARIABLES
#define NUMBER_VARIABLES AREST_NUMBER_VARIABLES
#endif

#ifdef AREST_NUMBER_FUNCTIONS
#define NUMBER_FUNCTIONS AREST_NUMBER_FUNCTIONS
#endif

#if defined(NUMBER_VARIABLES) && defined(NUMBER_FUNCTIONS)
  #define AREST_NUMBER_HANDLERS (NUMBER_VARIABLES + NUMBER_FUNCTIONS)
#elif defined(NUMBER_VARIABLES)
  #if defined(__AVR_ATmega1280__) || defined(ESP32) || defined(__AVR_ATmega2560__) || defined(CORE_WILDFIRE) || defined(ESP8266)
  #define NUMBER_FUNCTIONS 10
  #else
  #define NUMBER_FUNCTIONS 5
  #endif
  #define AREST_NUMBER_HANDLERS (NUMBER_VARIABLES + NUMBER_FUNCTIONS)
#elif defined(NUMBER_FUNCTIONS)
  #if defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__) || defined(CORE_WILDFIRE) || defined(ESP8266)|| defined(ESP32) || !defined(ADAFRUIT_CC3000_H)
  #define NUMBER_VARIABLES 10
  #else
  #define NUMBER_VARIABLES 5
  #endif
  #define AREST_NUMBER_HANDLERS (NUMBER_VARIABLES + NUMBER_FUNCTIONS)
#endif
// -------- end --------
```

Also the API of the library is the same as before:
```
template<typename T>
void variable(const char *name, T *var, bool quotable);

void function(const char *name, int (*f)(String));
```

### CODE REVIEW

**Comment by OidaTiftla** [comment]
Hi, thanks for your interest. No, they are both completely separated, because they are not necessary for the modifications in this pull request. But if they are merged, this pull request will fail to merge, because of some conflicting lines (as far as I tested it merging locally). But I'll update this branch if necessary :)

**Comment by marcoschwartz** [comment]
I just merged the two others :)

**Comment by OidaTiftla** [comment]
Ok, thanks :+1: I updated the branch

**Comment by marcoschwartz** [comment]
Merging this one :) However, I will run extended tests with all boards possible before releasing it to the official Arduino library manager.

**Comment by marcoschwartz** [comment]
And thanks for your work!

**Comment by OidaTiftla** [comment]
Thanks :)
I really like your library :+1:

**Comment by marcoschwartz** [comment]
Thanks! :) Seems to work just fine with all the boards I have, I'll push the change into the library manager as a new release and then test #239

**Pull request merged**
