### PR TITLE
Function can send String, and standard command can be disabled

### PR DESCRIPTION
**Pull request by lucalas**
Function can send String, and standard command can be disabled (analog, digital, mode).
I changed the return value of a function to return a string to client so we can send json for example instead of an integer.

In addition I thought that if i expose my api in internet, normal commands like analog, digital and mode, would be really insecure, so i added a define that help us to attach and detach them.

### CODE REVIEW

**Comment by gorhgorh** [comment]
why is this pr closed? Return a json object from function would be rad ? @lucalas are you using this atm?

**Comment by lucalas** [comment]
@gorhgorh the build didn't work at all, just for the case that i'm able to test.

At the moment I'm not able to build and test all cases to verify travis tests and i don't use Arduino board anymore, however I can try to recreate the pool request if you think could be a good feature.

**Comment by lucalas** [comment]
@gorhgorh  I think this PR #233 do the same thing but in a better way!

**Comment by gorhgorh** [comment]
thanks for your comments, I'll have a look a this PR

**Comment by Ellerbach** [comment]
@gorhgorh let me know if you have any question on the function returning string. I'm the  one who did the PR. Happy to help you if needed.

**Comment by gorhgorh** [comment]
thanks @Ellerbach, too bad this is pr is not merged, i see so many case where getting data as return of a function avoid having to expose, and make a request to a variable, as we had to do in the project we are using aRest with

**Comment by marcoschwartz** [comment]
Indeed, I am not sure about why this PR request was closed. If anyone want to submit a new one you are welcome to do so :)

**Pull request closed without merging**
