### PR TITLE
Json quoting

### PR DESCRIPTION
**Pull request by eykamp**
This PR will properly quote JSON values, generating properly formed JSON.  This will create a minor change in behavior when returning string values, which are currently not quoted.

Sorry if this is getting confusing -- I'm trying to keep things as atomic as possible, but my local tree is getting really messy, and it's hard to keep track of where we are in relation to one another.  I'm doing my best! 

Builds off of these PRs.  Merging them first will simplify this one.
(#194) Break out common code into functions
(#195) Streamline flow

### CODE REVIEW

**Comment by marcoschwartz** [comment]
Seems like I cannot merge this one as well - could you check? Thanks again for the amazing work you did on aREST!

**Comment by eykamp** [comment]
This should merge now.

**Comment by marcoschwartz** [comment]
Merged #194 , but now this one doesn't merge anymore

**Comment by eykamp** [comment]
Ok... if this builds, please merge this one and then let's see about the other one.

**Comment by marcoschwartz** [comment]
Now this one works :) However still an issue with #199

**Pull request merged**
